version: '3'

services:
  app-sippd-bappeda:
    build:
      context: ./SIPPDBappeda
      dockerfile: Dockerfile.dev
    container_name: app-sippd-bappeda
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./SIPPDBappeda:/var/www
      - ./SIPPDBappeda/docker/8.0/php/app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./SIPPDBappeda/docker/8.0/php/php.ini:/usr/local/etc/php/php.ini
      - ./SIPPDBappeda/docker/8.0/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./SIPPDBappeda/docker/8.0/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - dev

  #Nginx Service
  web-sippd-bappeda:
    image: nginx:alpine
    container_name: web-sippd-bappeda
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
    volumes:
      - ./SIPPDBappeda:/var/www
      - ./SIPPDBappeda/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./SIPPDBappeda/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev

networks:
   dev:
  